version: "3.7"

services:
  back-end:
    build: ./back-end
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://tictactoe:tictactoe@postgres:5432/tictactoe
      NODE_ENV: production
      PORT: 8081
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules

  postgres:
    image: postgres:11.2
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: tictactoe
      POSTGRES_PASSWORD: tictactoe
      POSTGRES_DB: tictactoe

  front-end:
    build: ./front-end
    environment:
      NODE_ENV: production
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
